# Generated by Django 4.2 on 2023-05-15 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageMyHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comName', models.CharField(max_length=128)),
                ('comAdress', models.CharField(max_length=128)),
                ('comZip', models.IntegerField(default=0)),
                ('comCity', models.CharField(max_length=128)),
                ('comDomain', models.CharField(max_length=128)),
                ('comPhone', models.IntegerField(default=0)),
                ('comEmail', models.EmailField(max_length=128)),
                ('comImage', models.ImageField(blank=True, null=True, upload_to='company')),
            ],
        ),
        migrations.CreateModel(
            name='t_heaterTechnologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heaName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='t_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houCity', models.CharField(max_length=128)),
                ('houPlot', models.IntegerField(default=0)),
                ('houSurface', models.FloatField(default=0.0)),
                ('houConstructionYear', models.IntegerField(default=0)),
                ('houFloor', models.IntegerField(default=0)),
                ('houRoom', models.IntegerField(default=0)),
                ('idxHeaterTechnologie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ManageMyHome.t_heatertechnologie')),
                ('idxUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='t_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='t_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worName', models.CharField(max_length=128)),
                ('worCost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('worDescription', models.TextField()),
                ('worStart', models.DateField()),
                ('worEnd', models.DateField()),
                ('worContract', models.FileField(blank=True, null=True, upload_to='work/contract')),
                ('worBillUrl', models.FileField(blank=True, null=True, upload_to='work/bill')),
                ('idxCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageMyHome.t_company')),
                ('idxProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageMyHome.t_project')),
            ],
        ),
        migrations.CreateModel(
            name='t_provide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idxHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageMyHome.t_house')),
                ('idxProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageMyHome.t_project')),
            ],
        ),
        migrations.CreateModel(
            name='t_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picImage', models.ImageField(blank=True, null=True, upload_to='house/images')),
                ('idxHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageMyHome.t_house')),
            ],
        ),
        migrations.CreateModel(
            name='t_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docFileUrl', models.FileField(blank=True, null=True, upload_to='house/documents')),
                ('idxHouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageMyHome.t_house')),
            ],
        ),
        migrations.CreateModel(
            name='t_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conFirstname', models.CharField(max_length=128)),
                ('conLastname', models.CharField(max_length=128)),
                ('conFunction', models.CharField(max_length=128)),
                ('conEmail', models.EmailField(max_length=128)),
                ('conPhone', models.IntegerField(default=0)),
                ('idxCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageMyHome.t_company')),
            ],
        ),
    ]
