# Generated by Django 4.2 on 2023-05-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageMyHome', '0002_t_company_t_heatertechnologie_t_house_t_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_project',
            name='idxUser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
